### ISSUE TITLE
Bug: Inference on cuda results in fixed bounding box offset!

### ISSUE THREAD

**Issue by corkillj** [ternaus/retinaface#38]
I have noticed that if you infer using cuda rather than the cpu, the landmarks are still spot on but the bounding boxes will be shifted to the right significantly. Anyone have a clue what could cause this? 

Output with "cpu":
![image](https://user-images.githubusercontent.com/71826032/142601621-8b6f140a-8bb0-4859-9e09-65949cf75d3e.png)

Output with "cuda":
![image](https://user-images.githubusercontent.com/71826032/142601721-263f0c1f-a943-43aa-bd01-884c571a9cc5.png)

**Comment by corkillj** [comment]
I have found the bug! For the final annotation return value in the model.predict_jsons() function the tensor containing the bounding boxes is moved to cpu and converted to a numpy array. But the later resizing operation is done on the original tensor variable rather than on the new numpy one. When running on cpu this bug is not apparent because the tensor is not copied when converted to a numpy array but only a new reference is created.

Original:
```python
boxes_np = boxes.cpu().numpy()
landmarks_np = landmarks.cpu().numpy()
resize_coeff = original_height / transformed_height

boxes *= resize_coeff
```

Modified:
```python
boxes_np = boxes.cpu().numpy()
landmarks_np = landmarks.cpu().numpy()
resize_coeff = original_height / transformed_height

boxes_np *= resize_coeff
```

**Comment by ternaus** [comment]
Thanks. Fixed.
