### ISSUE TITLE
Why def _pad_to_square do not to adjust the landmark?

### ISSUE THREAD

**Issue by Tallisgo** [ternaus/retinaface#7]
When resize the image to 640*640, if  landmarks change or not? And why do not adjust them? @ternaus

**Comment by ternaus** [comment]
What do you mean? Everything should be resized as expected.

**Comment by Tallisgo** [comment]
Thank you for your reply. I jus twonder  _resize_subtract_mean() in data_augment.py only resize the image but do not change the values of landmarks.

**Comment by ternaus** [comment]
Could you please point me to the line in the code you are confused about?
